name: Build and Push Container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MARAIMADESIDA }}
          password: ${{ secrets.LATIFAT23 }}

      - name: Build and push container
        run: |
          docker build -t mariamadesida/assignment6:prod .
          docker push mariamadesida/assignment6:prod
